### ISSUE TITLE
cannot pip install scriptine on mac

### ISSUE THREAD

**Issue by chensaics** [olt/scriptine#5]
Collecting scriptine
  Using cached scriptine-0.2.1.tar.gz (32 kB)
    ERROR: Command errored out with exit status 1:
     command: /opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/r5/7f904m0j0hj3qcz5k66c1nn80000gn/T/pip-install-dopm7xmd/scriptine/setup.py'"'"'; __file__='"'"'/private/var/folders/r5/7f904m0j0hj3qcz5k66c1nn80000gn/T/pip-install-dopm7xmd/scriptine/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/r5/7f904m0j0hj3qcz5k66c1nn80000gn/T/pip-pip-egg-info-3bjcpqh3
         cwd: /private/var/folders/r5/7f904m0j0hj3qcz5k66c1nn80000gn/T/pip-install-dopm7xmd/scriptine/
    Complete output (10 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/r5/7f904m0j0hj3qcz5k66c1nn80000gn/T/pip-install-dopm7xmd/scriptine/setup.py", line 1, in <module>
        import scriptine
      File "/private/var/folders/r5/7f904m0j0hj3qcz5k66c1nn80000gn/T/pip-install-dopm7xmd/scriptine/scriptine/__init__.py", line 1, in <module>
        from scriptine._path import path
      File "/private/var/folders/r5/7f904m0j0hj3qcz5k66c1nn80000gn/T/pip-install-dopm7xmd/scriptine/scriptine/_path.py", line 906
        def mkdir(self, mode=0777):
                                ^
    SyntaxError: invalid token
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by olt** [comment]
Scriptine is not compatible with Python 3.
